name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install markdown lint dependencies
        run: |
          npm install remark-cli remark-preset-lint-consistent

      - name: Run markdown lint
        run: | 
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent 

